version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ankatech-net

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npx prisma generate && npx tsx watch src/index.ts"
    depends_on:
      - db
    networks:
      - ankatech-net
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/meubanco

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - ankatech-net
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000

volumes:
  db_data:

networks:
  ankatech-net:
    driver: bridge
